### ISSUE TITLE
terminal-notifier の代替を探す

### ISSUE THREAD

**Issue by otofune** [otofune/dotfiles#11]
Linux でも動くやつ

**Comment by rinsuki** [comment]
notify-send?

**Comment by rokoucha** [comment]
https://wiki.archlinux.jp/index.php/%E3%83%87%E3%82%B9%E3%82%AF%E3%83%88%E3%83%83%E3%83%97%E9%80%9A%E7%9F%A5#.E3.83.97.E3.83.AD.E3.82.B0.E3.83.A9.E3.83.9F.E3.83.B3.E3.82.B0.E3.81.A7.E3.81.AE.E4.BD.BF.E3.81.84.E6.96.B9

**Comment by otofune** [comment]
やっぱ分岐書くべき？
fish の function として生やすかぁ

**Comment by otofune** [comment]
いったんグローバルで使わなくなったので問題ない
